# Generated by Django 3.1.8 on 2021-05-02 14:48

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_change_delete_to_timestamp'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDailyCarbonFootprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('carbon_footprint', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_carbon_footprints', to='trips.device')),
            ],
            options={
                'ordering': (('device', 'date'),),
                'unique_together': {('device', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EmissionBudgetLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('carbon_footprint', models.FloatField(help_text='Amount of carbon emissions per resident per year (in kgs of CO2e.) to reach this level', verbose_name='Maximum emission amount')),
                ('year', models.PositiveIntegerField(help_text='Year to which this level applies', verbose_name='Year')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'Emission budget level',
                'verbose_name_plural': 'Emission budget levels',
                'ordering': ('year', 'carbon_footprint'),
                'unique_together': {('identifier', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='DailyEmissionBudget',
        ),
    ]
