# Generated by Django 3.1.8 on 2021-06-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_add_emission_budget_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedailycarbonfootprint',
            name='average_footprint_used',
            field=models.BooleanField(default=False),
        ),
    ]
