# Generated by Django 3.1.9 on 2021-06-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_add_prize_model'),
        ('budget', '0003_add_average_footprint_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedailycarbonfootprint',
            options={'ordering': ('device', 'date')},
        ),
        migrations.AlterField(
            model_name='devicedailycarbonfootprint',
            name='carbon_footprint',
            field=models.FloatField(help_text='Carbon footprint in kg CO2e'),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_month_start', models.DateField(help_text='First day of the month for which the prize is awarded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='budget.emissionbudgetlevel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='trips.device')),
            ],
        ),
    ]
