# Generated by Django 3.1.9 on 2021-10-14 15:12

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    AccountDailyCarbonFootprint = apps.get_model('budget', 'AccountDailyCarbonFootprint')
    for footprint in AccountDailyCarbonFootprint.objects.all():
        assert footprint.account is None
        assert footprint.device.account is not None
        footprint.account = footprint.device.account
        footprint.save()


def reverse_func(apps, schema_editor):
    AccountDailyCarbonFootprint = apps.get_model('budget', 'AccountDailyCarbonFootprint')
    for footprint in AccountDailyCarbonFootprint.objects.all():
        assert footprint.account.devices.count() == 1
        footprint.device = footprint.account.devices.first()
        footprint.account = None
        footprint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_create_accounts'),
        ('budget', '0004_add_prize_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceDailyCarbonFootprint',
            new_name='AccountDailyCarbonFootprint',
        ),
        migrations.AlterModelOptions(
            name='accountdailycarbonfootprint',
            options={'ordering': ('account', 'date')},
        ),
        # Add null=True only temporarily during migration
        migrations.AddField(
            model_name='accountdailycarbonfootprint',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_carbon_footprints', to='trips.account'),
        ),
        migrations.AlterUniqueTogether(
            name='accountdailycarbonfootprint',
            unique_together={('account', 'date')},
        ),
        # Allow null values for device to make this migration reversible
        migrations.AlterField(
            model_name='accountdailycarbonfootprint',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_carbon_footprints', to='trips.device', null=True)
        ),
        # Set values for account
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='accountdailycarbonfootprint',
            name='device',
        ),
        # Remove temporary null=True
        migrations.AlterField(
            model_name='accountdailycarbonfootprint',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_carbon_footprints', to='trips.account'),
        ),
    ]
