# Generated by Django 3.1.9 on 2022-08-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0027_add_device_last_processed_data_received_at'),
        ('budget', '0004_add_prize_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedailycarbonfootprint',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.CreateModel(
            name='DeviceDailyHealthImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('bicycle_mins', models.FloatField(help_text='Minutes spent bicycling')),
                ('walk_mins', models.FloatField(help_text='Minutes spent walking')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_health_impacts', to='trips.device')),
            ],
            options={
                'ordering': ('device', 'date'),
                'unique_together': {('device', 'date')},
            },
        ),
    ]
