# Generated by Django 3.1.9 on 2021-10-14 15:12

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Prize = apps.get_model('budget', 'Prize')
    for footprint in Prize.objects.all():
        assert footprint.account is None
        assert footprint.device.account is not None
        footprint.account = footprint.device.account
        footprint.save()


def reverse_func(apps, schema_editor):
    Prize = apps.get_model('budget', 'Prize')
    for footprint in Prize.objects.all():
        assert footprint.account.devices.count() == 1
        footprint.device = footprint.account.devices.first()
        footprint.account = None
        footprint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_create_accounts'),
        ('budget', '0005_move_footprints_to_account_model'),
    ]

    operations = [
        # Add null=True only temporarily during migration
        migrations.AddField(
            model_name='prize',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='trips.account'),
        ),
        # Allow null values for device to make this migration reversible
        migrations.AlterField(
            model_name='prize',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='trips.device', null=True)
        ),
        # Set values for account
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='prize',
            name='device',
        ),
        # Remove temporary null=True
        migrations.AlterField(
            model_name='prize',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='trips.account'),
        ),
    ]
