# Generated by Django 3.1.8 on 2021-08-30 08:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Identifier')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('wfs_url', models.URLField(null=True)),
                ('wfs_type_name', models.CharField(max_length=200, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=20, verbose_name='Identifier')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(db_index=True, srid=settings.LOCAL_SRS)),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.areatype')),
            ],
            options={
                'unique_together': {('type', 'identifier')},
            },
        ),
    ]
