# Generated by Django 3.1.8 on 2021-09-06 11:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_add_prize_model'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('primary_mode_other', models.IntegerField(choices=[(1, 'Multi-modal with no primary transport mode'), (2, 'Multi-modal with public transport')], null=True)),
                ('length', models.FloatField()),
                ('carbon_footprint', models.FloatField()),
                ('start_loc', django.contrib.gis.db.models.fields.PointField(srid=3067)),
                ('end_loc', django.contrib.gis.db.models.fields.PointField(srid=3067)),
                ('primary_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.transportmode')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='DailyModeSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('length', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.area')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.transportmode')),
            ],
            options={
                'unique_together': {('date', 'area')},
            },
        ),
    ]
