# Generated by Django 3.1.8 on 2021-09-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_add_prize_model'),
        ('analytics', '0002_add_helper_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailymodesummary',
            unique_together={('date', 'area', 'mode')},
        ),
        migrations.CreateModel(
            name='DailyTripSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('mode_specifier', models.CharField(max_length=20, null=True)),
                ('trips', models.IntegerField()),
                ('dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analytics.area')),
                ('mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.transportmode')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analytics.area')),
            ],
            options={
                'unique_together': {('date', 'origin', 'dest', 'mode', 'mode_specifier')},
            },
        ),
    ]
