# Generated by Django 3.1.8 on 2021-09-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_add_more_summary_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatype',
            name='topojson',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='analytics.areatype'),
        ),
    ]
