# Generated by Django 3.1.8 on 2021-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_add_topojson_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='properties',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='areatype',
            name='properties_meta',
            field=models.JSONField(null=True),
        ),
    ]
