# Generated by Django 3.1.9 on 2021-12-20 20:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_add_area_extra_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, null=True, srid=3067),
        ),
        migrations.AddField(
            model_name='areatype',
            name='geojson',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='areatype',
            name='is_poi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailymodesummary',
            name='trips',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailytripsummary',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tripsummary',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tripsummary',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
