# Generated by Django 3.1.9 on 2022-01-05 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_add_new_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatype',
            name='daily_lengths_date_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='areatype',
            name='daily_trips_date_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), blank=True, null=True, size=None),
        ),
    ]
