# Generated by Django 3.1.9 on 2022-01-07 07:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_device_account_key'),
        ('analytics', '0007_add_area_type_date_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatype',
            name='daily_poi_trips_date_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='DailyPoiTripSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('is_inbound', models.BooleanField()),
                ('mode_specifier', models.CharField(max_length=20, null=True)),
                ('trips', models.IntegerField()),
                ('length', models.FloatField(null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analytics.area')),
                ('mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.transportmode')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_summaries', to='analytics.area')),
            ],
            options={
                'unique_together': {('date', 'poi', 'area', 'is_inbound', 'mode', 'mode_specifier')},
            },
        ),
    ]
