# Generated by Django 3.1.9 on 2022-02-09 10:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_keep_poi_summaries_separate'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='geometry_masked',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(db_index=True, null=True, srid=3067),
        ),
    ]
