# Generated by Django 3.1.9 on 2022-02-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_add_masked_geometry_to_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='areatype',
            name='properties_meta',
        ),
        migrations.CreateModel(
            name='AreaProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('area_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_meta', to='analytics.areatype')),
            ],
            options={
                'ordering': ('area_type', 'order'),
                'unique_together': {('area_type', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='AreaPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='analytics.area')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_values', to='analytics.areaproperty')),
            ],
            options={
                'unique_together': {('area', 'property')},
            },
        ),
    ]
