# Generated by Django 3.1.9 on 2022-05-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_device_account_key'),
        ('analytics', '0010_area_properties_to_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDailyAPIActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nr_queries', models.PositiveIntegerField(default=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_api_activity', to='trips.device')),
            ],
            options={
                'unique_together': {('device', 'date')},
            },
        ),
    ]
