# Generated by Django 3.1.8 on 2021-05-04 14:05

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='lead_paragraph',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tagline',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
