# Generated by Django 3.1.9 on 2022-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0028_add_device_groups'),
        ('pages', '0005_visualisationguidepage_visualisationguidepageindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='device_groups',
            field=models.ManyToManyField(blank=True, to='trips.DeviceGroup'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='device_groups',
            field=models.ManyToManyField(blank=True, to='trips.DeviceGroup'),
        ),
    ]
