# Generated by Django 3.1.9 on 2022-08-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_add_device_groups_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='hidden_from_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infopage',
            name='static_identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
