# Generated by Django 3.1.9 on 2022-08-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
            CREATE SCHEMA IF NOT EXISTS gtfs;
            CREATE TABLE IF NOT EXISTS gtfs.feed_info (
                feed_index serial PRIMARY KEY, -- tracks uploads, avoids key collisions
                feed_publisher_name text default null,
                feed_publisher_url text default null,
                feed_timezone text default null,
                feed_lang text default null,
                feed_version text default null,
                feed_start_date date default null,
                feed_end_date date default null,
                feed_id text default null,
                feed_contact_url text default null,
                feed_contact_email text default null,
                feed_download_date date,
                feed_file text
            );
            CREATE TABLE IF NOT EXISTS gtfs.route_types (
                route_type int PRIMARY KEY,
                description text
            );
            CREATE TABLE IF NOT EXISTS gtfs.routes (
                feed_index int not null,
                route_id text,
                agency_id text,
                route_short_name text default '',
                route_long_name text default '',
                route_desc text default '',
                route_type int REFERENCES gtfs.route_types(route_type),
                route_url text,
                route_color text,
                route_text_color text,
                route_sort_order integer default null,
                CONSTRAINT routes_pkey PRIMARY KEY (feed_index, route_id),
                CONSTRAINT routes_feed_fkey FOREIGN KEY (feed_index)
                    REFERENCES gtfs.feed_info (feed_index) ON DELETE CASCADE
            );
        """),
    ]
