# Generated by Django 3.1.7 on 2021-03-04 09:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.RunSQL("""
            CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
        """, reverse_sql=""),
        migrations.RunSQL(sql=f"""
            CREATE TABLE "transitrt_vehiclelocation" (
                "direction_ref" varchar(5) NULL,
                "vehicle_ref" varchar(30) NOT NULL,
                "journey_ref" varchar(30) NOT NULL,
                "vehicle_journey_ref" varchar(50) NOT NULL,
                "time" timestamp with time zone NOT NULL,
                "loc" geometry(POINT,{settings.LOCAL_SRS}) NOT NULL,
                "gtfs_feed_id" integer NULL,
                "gtfs_route_id" text NULL,
                "bearing" double precision NULL,
                CONSTRAINT "transitrt_vehiclelocation_gtfs_route_id"
                    FOREIGN KEY ("gtfs_feed_id", "gtfs_route_id")
                        REFERENCES "gtfs"."routes" ("feed_index", "route_id")
                        ON DELETE SET NULL
            );
        """, reverse_sql="""
            DROP TABLE "transitrt_vehiclelocation" CASCADE;
        """),
        migrations.RunSQL("""
            SELECT create_hypertable(
                'transitrt_vehiclelocation', 'time',
                chunk_time_interval => INTERVAL '1 day'
            );
        """, reverse_sql=""),
        migrations.RunSQL("""
            CREATE INDEX "transitrt_vehiclelocation_loc_id" ON "transitrt_vehiclelocation" USING GIST ("loc");
        """, reverse_sql=""),
        migrations.RunSQL("""
            CREATE UNIQUE INDEX on "transitrt_vehiclelocation" (time, vehicle_journey_ref);
        """, reverse_sql=""),
    ]
