# Generated by Django 3.1.7 on 2021-03-04 09:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
            CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
        """),
        migrations.RunSQL(sql=f"""
            CREATE TABLE "trips_ingest_location" (
                "time" timestamp with time zone NOT NULL,
                "uuid" uuid NOT NULL,
                "loc" geometry(POINT,{settings.LOCAL_SRS}) NOT NULL,
                "loc_error" double precision NULL,
                "atype" varchar(20) NULL,
                "aconf" double precision NULL,
                "speed" double precision NULL,
                "heading" double precision NULL,
                "sensor_data_count" integer NULL CHECK ("sensor_data_count" >= 0)
            );
        """, reverse_sql="""
            DROP TABLE "trips_ingest_location" CASCADE;
        """),
        migrations.RunSQL("""
            SELECT create_hypertable('trips_ingest_location', 'time', 'uuid', 8);
        """),
        migrations.RunSQL("""
            CREATE UNIQUE INDEX on "trips_ingest_location" (time, uuid);
        """),
    ]
