# Generated by Django 3.1.7 on 2021-03-04 11:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips_ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('loc_error', models.FloatField(null=True)),
                ('atype', models.CharField(choices=[('unknown', 'Unknown'), ('still', 'Still'), ('on_foot', 'On foot'), ('walking', 'Walking'), ('running', 'Running'), ('on_bicycle', 'On bicycle'), ('in_vehicle', 'In vehicle')], max_length=20, null=True)),
                ('aconf', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('heading', models.FloatField(null=True)),
                ('sensor_data_count', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'trips_ingest_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorSample',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('type', models.CharField(choices=[('acce', 'Accelerometer'), ('gyro', 'Gyroscope')], max_length=20)),
            ],
            options={
                'db_table': 'trips_ingest_sensorsample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationImport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('acc', models.IntegerField(null=True)),
                ('atype', models.CharField(max_length=30, null=True)),
                ('aconf', models.IntegerField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('heading', models.FloatField(null=True)),
                ('ms', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorSampleImport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
                ('ms', models.IntegerField(null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
