# Generated by Django 3.1.7 on 2021-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_ingest', '0002_add_import_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimport',
            name='created_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locationimport',
            name='debug',
            field=models.IntegerField(null=True),
        ),
    ]
