# Generated by Django 3.1.7 on 2021-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_ingest', '0004_add_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatImport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('ms', models.IntegerField(null=True)),
                ('uid', models.CharField(max_length=50)),
                ('debug', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'unique_together': {('uuid', 'time')},
            },
        ),
    ]
