# Generated by Django 3.1.7 on 2021-04-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_ingest', '0005_add_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=20, null=True)),
                ('system_version', models.CharField(max_length=20, null=True)),
                ('brand', models.CharField(max_length=20, null=True)),
                ('model', models.CharField(max_length=20, null=True)),
                ('created_at', models.IntegerField(null=True)),
            ],
        ),
    ]
