# Generated by Django 3.1.8 on 2021-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_ingest', '0006_add_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('received_at', models.DateTimeField()),
            ],
        ),
    ]
