# Generated by Django 3.1.8 on 2021-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_ingest', '0007_add_receive_data_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedata',
            options={'ordering': ('received_at',)},
        ),
        migrations.AddField(
            model_name='receivedata',
            name='import_failed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='receivedata',
            name='imported_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivedata',
            name='received_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
