# Generated by Django 3.1.7 on 2021-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_ingest', '0008_add_receivedata_fields'),
    ]

    operations = [
        migrations.RunSQL("""
            ALTER TABLE "trips_ingest_location" ADD COLUMN "speed_error" double precision NULL;
            ALTER TABLE "trips_ingest_location" ADD COLUMN "altitude" double precision NULL;
            ALTER TABLE "trips_ingest_location" ADD COLUMN "altitude_error" double precision NULL;
            ALTER TABLE "trips_ingest_location" ADD COLUMN "heading_error" double precision NULL;
            ALTER TABLE "trips_ingest_location" ADD COLUMN "odometer" double precision NULL;
            ALTER TABLE "trips_ingest_location" ADD COLUMN "is_moving" BOOLEAN NULL;
            ALTER TABLE "trips_ingest_location" ADD COLUMN "battery_charging" BOOLEAN NULL;
        """, reverse_sql="""
            ALTER TABLE "trips_ingest_location" DROP COLUMN "speed_error";
            ALTER TABLE "trips_ingest_location" DROP COLUMN "altitude";
            ALTER TABLE "trips_ingest_location" DROP COLUMN "altitude_error";
            ALTER TABLE "trips_ingest_location" DROP COLUMN "heading_error";
            ALTER TABLE "trips_ingest_location" DROP COLUMN "odometer";
            ALTER TABLE "trips_ingest_location" DROP COLUMN "is_moving";
            ALTER TABLE "trips_ingest_location" DROP COLUMN "battery_charging";
        """),
    ]
