# Generated by Django 3.1.8 on 2021-05-17 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('trips_ingest', '0011_add_debug_log_model'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP TABLE IF EXISTS "trips_ingest_sensorsample" CASCADE;
        """),
    ]
