# Generated by Django 3.1.8 on 2021-05-17 22:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips_ingest', '0012_drop_old_sensors_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('uuid', models.UUIDField()),
                ('x', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('y', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('z', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('t', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('type', models.CharField(choices=[('acce', 'Accelerometer'), ('gyro', 'Gyroscope')], max_length=20)),
            ],
            options={
                'db_table': 'trips_ingest_sensorsample',
                'ordering': ('uuid', 'time'),
                'managed': True,
                'unique_together': {('uuid', 'time', 'type')},
            },
        ),
    ]
