# Generated by Django 3.1.8 on 2021-06-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_add_device_friendly_name'),
        ('trips_ingest', '0013_generate_sensors_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedata',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_data', to='trips.device'),
        ),
    ]
