# Generated by Django 3.1.9 on 2023-07-12 11:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legs',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='partisipants',
            new_name='partisipant',
        ),
        migrations.AlterField(
            model_name='legs',
            name='end_loc',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='legs',
            name='start_loc',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='legs',
            name='transport_mode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
