# Generated by Django 3.1.9 on 2023-07-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20230704_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partisipants',
            name='partisipant_approved',
        ),
    ]
