# Generated by Django 3.1.9 on 2023-08-02 06:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20230801_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='legs',
            name='end_loc',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='legs',
            name='start_loc',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
