# Generated by Django 3.1.9 on 2023-07-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20230712_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='legs',
            name='original_leg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='original_trip',
            field=models.BooleanField(default=True),
        ),
    ]
