# Generated by Django 3.1.9 on 2023-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20230712_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legs',
            name='original_leg',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='original_trip',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
