# Generated by Django 3.1.9 on 2023-08-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20230802_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partisipants',
            old_name='partisipant_approved',
            new_name='approved',
        ),
    ]
