# Generated by Django 3.1.9 on 2023-07-04 11:54

from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_remove_partisipants_partisipant_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='partisipants',
            name='partisipant_approved',
            field=models.CharField(choices=[(poll.models.approved_choice['No'], 'No'), (poll.models.approved_choice['Yes'], 'Yes')], default=poll.models.approved_choice['No'], max_length=255),
        ),
    ]
