# Generated by Django 3.1.9 on 2023-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20230712_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='legs',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
