# Generated by Django 3.1.9 on 2023-07-19 06:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20230712_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('time', models.DateTimeField()),
                ('speed', models.FloatField()),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='poll.legs')),
            ],
            options={
                'ordering': ('leg', 'time'),
            },
        ),
    ]
