# Generated by Django 3.1.9 on 2023-08-03 07:29

from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20230803_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='purpose',
            field=models.CharField(choices=[(poll.models.Trip_purpose['tyo'], 'työ'), (poll.models.Trip_purpose['opiskelu'], 'opiskelu'), (poll.models.Trip_purpose['tyoasia'], 'työasia/opiskelu'), (poll.models.Trip_purpose['vapaaaika'], 'vapaa-aika'), (poll.models.Trip_purpose['ostos'], 'ostos'), (poll.models.Trip_purpose['muu'], 'muu asiointi ja kyyditseminen'), (poll.models.Trip_purpose['tyhja'], 'tyhja')], default='tyhja', max_length=20),
        ),
    ]
