# Generated by Django 3.1.9 on 2023-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_legslocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legs',
            name='end_loc',
        ),
        migrations.RemoveField(
            model_name='legs',
            name='start_loc',
        ),
        migrations.AlterField(
            model_name='legslocation',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
