# Generated by Django 3.1.9 on 2023-07-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20230726_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='survey_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.surveyinfo'),
        ),
    ]
