# Generated by Django 3.1.9 on 2023-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_questions_survey_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legs',
            name='trip_length',
            field=models.FloatField(null=True),
        ),
    ]
