# Generated by Django 3.1.9 on 2023-07-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20230726_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
