# Generated by Django 3.1.9 on 2023-09-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20230803_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='partisipants',
            name='registered_to_survey_at',
            field=models.DateTimeField(null=True),
        ),
    ]
