# Generated by Django 3.1.6 on 2021-02-02 12:14

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
    ]
