# Generated by Django 3.1.6 on 2021-02-02 12:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('uuid', models.UUIDField()),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('acc', models.IntegerField(null=True)),
                ('atype', models.CharField(choices=[('unknown', 'Unknown'), ('still', 'Still'), ('on_foot', 'On foot'), ('walking', 'Walking'), ('running', 'Running'), ('on_bicycle', 'On bicycle'), ('in_vehicle', 'In vehicle')], max_length=20, null=True)),
                ('aconf', models.IntegerField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('heading', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationImport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('acc', models.IntegerField(null=True)),
                ('atype', models.CharField(max_length=30, null=True)),
                ('aconf', models.IntegerField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('heading', models.FloatField(null=True)),
                ('ms', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['uuid', '-time'], name='trips_locat_uuid_d186fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('uuid', 'time')},
        ),
    ]
