# Generated by Django 3.1.6 on 2021-02-02 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('length', models.FloatField()),
                ('carbon_footprint', models.FloatField()),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.installation')),
            ],
        ),
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Identifier')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('emission_factor', models.FloatField(help_text='Emission factor of transport mode in g (CO2e)/passenger-km', null=True, verbose_name='Emission factor')),
            ],
        ),
        migrations.CreateModel(
            name='LegLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('time', models.DateTimeField()),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.leg')),
            ],
        ),
        migrations.AddField(
            model_name='leg',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.transportmode'),
        ),
    ]
