# Generated by Django 3.1.6 on 2021-02-02 14:11

from django.db import migrations

DEFAULT_TRANSPORT_MODES = (
    ('still', 'Still', 0),
    ('walk', 'Walking', 0),
    ('car', 'Car', 185.6),
    ('bicycle', 'Bicycle', 5),
    ('bus', 'Bus', 63.2),
    ('tram', 'Tram', 5.6),
    ('train', 'Train', 5.2),
)


def forwards_func(apps, schema_editor):
    TransportMode = apps.get_model("trips", "TransportMode")
    db_alias = schema_editor.connection.alias
    TransportMode.objects.using(db_alias).bulk_create([
        TransportMode(identifier=x[0], label=x[1], emission_factor=x[2])
        for x in DEFAULT_TRANSPORT_MODES
    ])


def reverse_func(apps, schema_editor):
    TransportMode = apps.get_model("trips", "TransportMode")
    db_alias = schema_editor.connection.alias
    TransportMode.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_add_new_models'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
