# Generated by Django 3.1.6 on 2021-02-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_default_transport_modes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leglocation',
            options={'ordering': ('leg', 'time')},
        ),
        migrations.AlterModelOptions(
            name='transportmode',
            options={'verbose_name': 'Transport mode', 'verbose_name_plural': 'Transport modes'},
        ),
        migrations.RemoveField(
            model_name='leg',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='location',
            name='acc',
        ),
        migrations.RenameField(
            model_name='transportmode',
            old_name='label', new_name='name',
        ),
        migrations.AddField(
            model_name='leglocation',
            name='speed',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='loc_error',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='aconf',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.installation')),
            ],
        ),
        migrations.AddField(
            model_name='leg',
            name='trip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trips.trip'),
            preserve_default=False,
        ),
    ]
