# Generated by Django 3.1.6 on 2021-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_rename_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('uuid', models.UUIDField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('type', models.CharField(choices=[('acce', 'Accelerometer'), ('gyro', 'Gyroscope')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SensorSampleImport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
                ('ms', models.IntegerField(null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Installation',
            new_name='Device',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='installation',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='transportmode',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='sensorsample',
            index=models.Index(fields=['uuid', '-time'], name='trips_senso_uuid_89b35d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sensorsample',
            unique_together={('uuid', 'time')},
        ),
    ]
