# Generated by Django 3.1.6 on 2021-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_add_sensor_sample_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sensor_data_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
