# Generated by Django 3.1.7 on 2021-03-05 11:33

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_add_location_sensor_data_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationImport',
        ),
        migrations.DeleteModel(
            name='SensorSample',
        ),
        migrations.DeleteModel(
            name='SensorSampleImport',
        ),
        migrations.AlterModelOptions(
            name='leg',
            options={'ordering': ('trip', 'started_at')},
        ),
        migrations.AddField(
            model_name='leg',
            name='end_loc',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leg',
            name='start_loc',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='ended_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='started_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
