# Generated by Django 3.1.7 on 2021-03-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_models_moved_elsewhere'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnableEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('enabled', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enable_events', to='trips.device')),
            ],
            options={
                'get_latest_by': 'time',
            },
        ),
        migrations.AddIndex(
            model_name='enableevent',
            index=models.Index(fields=['device', '-time'], name='trips_enabl_device__791f9a_idx'),
        ),
    ]
