# Generated by Django 3.1.7 on 2021-03-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_add_enable_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'get_latest_by': 'legs__started_at'},
        ),
        migrations.AddField(
            model_name='leg',
            name='mode_confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='nr_passengers',
            field=models.IntegerField(null=True),
        ),
    ]
