# Generated by Django 3.1.7 on 2021-03-29 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_add_new_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leg',
            options={'ordering': ('trip', 'start_time')},
        ),
        migrations.RenameField(
            model_name='leg',
            old_name='ended_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='leg',
            old_name='started_at',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='leg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leg',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leg',
            name='estimated_mode',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trips.transportmode'),
        ),
        migrations.AddField(
            model_name='leg',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='user_corrected_mode',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trips.transportmode'),
        ),
        migrations.CreateModel(
            name='UserLegUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_updates', to='trips.leg')),
            ],
            options={
                'ordering': ('leg', 'created_at'),
            },
        ),
    ]
