# Generated by Django 3.1.7 on 2021-04-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_rename_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='system_version',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
