# Generated by Django 3.1.7 on 2021-04-26 10:46

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_add_device_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'get_latest_by': 'legs__start_time'},
        ),
        migrations.AddField(
            model_name='transportmode',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs', to='trips.transportmode'),
        ),
        migrations.CreateModel(
            name='TransportModeVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Identifier')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('emission_factor', models.FloatField(help_text='Emission factor of transport mode in g (CO2e)/passenger-km', null=True, verbose_name='Emission factor')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='trips.transportmode')),
            ],
            options={
                'verbose_name': 'Transport mode variant',
                'verbose_name_plural': 'Transport mode variants',
            },
        ),
        migrations.AddField(
            model_name='leg',
            name='mode_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs', to='trips.transportmodevariant'),
        ),
        migrations.AddField(
            model_name='leg',
            name='user_corrected_mode_variant',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trips.transportmodevariant'),
        ),
    ]
