# Generated by Django 3.1.7 on 2021-04-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_add_mode_variants_and_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
