# Generated by Django 3.1.8 on 2021-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_change_delete_to_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='received_at',
            field=models.DateTimeField(null=True),
        ),
    ]
