# Generated by Django 3.1.8 on 2021-05-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_add_leg_received_at_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportmodevariant',
            unique_together={('mode', 'identifier')},
        ),
    ]
