# Generated by Django 3.1.8 on 2021-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_make_device_model_longer'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='debug_log_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='debugging_enabled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
