# Generated by Django 3.1.8 on 2021-05-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_add_device_debug_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='custom_config',
            field=models.JSONField(null=True),
        ),
    ]
