# Generated by Django 3.1.9 on 2021-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_add_device_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_summary_notification_month',
            field=models.DateField(blank=True, help_text='First day of the month for which the last monthly summary notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='welcome_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
