# Generated by Django 3.1.8 on 2021-11-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_add_prize_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundInfoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_info_questions', to='trips.device')),
            ],
            options={
                'ordering': ('device', 'question'),
            },
        ),
    ]
