# Generated by Django 3.1.9 on 2021-10-14 14:54

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Account = apps.get_model('trips', 'Account')
    Device = apps.get_model('trips', 'Device')
    assert not Account.objects.exists()
    for device in Device.objects.all():
        assert device.account is None
        device.account = Account.objects.create()
        device.save()


def reverse_func(apps, schema_editor):
    Account = apps.get_model('trips', 'Account')
    Device = apps.get_model('trips', 'Device')
    for device in Device.objects.all():
        device.account = None
        device.save()
    Account.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0025_add_account_model'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='device',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='trips.account'),
        ),
    ]
