# Generated by Django 3.1.9 on 2021-12-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0025_add_background_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='account_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
