# Generated by Django 3.1.9 on 2022-08-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0027_add_device_last_processed_data_received_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('devices', models.ManyToManyField(blank=True, related_name='groups', to='trips.Device')),
            ],
        ),
    ]
