# Generated by Django 3.1.9 on 2022-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0028_add_device_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='health_impact_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
