# Generated by Django 3.1.9 on 2023-07-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0029_add_health_impact_enabled_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='registered_to_survey_at',
            field=models.DateTimeField(null=True),
        ),
    ]
