# Generated by Django 3.1.9 on 2021-06-01 13:56

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('monthly_summary', 'Monthly summary'), ('welcome_message', 'Welcome message'), ('no_recent_trips', 'No recent trips')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('i18n', modeltrans.fields.TranslationField(fields=('title', 'body'), required_languages=(), virtual_fields=True)),
            ],
        ),
    ]
