# Generated by Django 3.1.9 on 2021-06-04 10:36

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0022_add_device_friendly_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('monthly_summary', 'Monthly summary'), ('welcome_message', 'Welcome message'), ('no_recent_trips', 'No recent trips')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('i18n', modeltrans.fields.TranslationField(fields=('title', 'body'), required_languages=(), virtual_fields=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.device')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
        ),
    ]
