# Generated by Django 3.1.9 on 2021-06-24 14:28

from django.db import migrations, models


def migrate_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    qs = NotificationTemplate.objects.filter(event_type='monthly_summary_bronze')
    qs.update(event_type='monthly_summary_geq_bronze')


def migrate_notification_templates_reverse(apps, schema_editor):
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    qs = NotificationTemplate.objects.filter(event_type='monthly_summary_geq_bronze')
    qs.update(event_type='monthly_summary_bronze')


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_split_monthly_summary_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('monthly_summary_gold', 'Monthly summary (gold-level budget)'), ('monthly_summary_silver', 'Monthly summary (silver-level budget)'), ('monthly_summary_geq_bronze', 'Monthly summary (bronze-level budget or worse)'), ('welcome_message', 'Welcome message'), ('no_recent_trips', 'No recent trips')], max_length=26),
        ),
    ]
